python cc_examples.py 10.0 1
python cc_examples.py 3.0 2
python cc_examples.py 0.0 3
python dft_examples.py 0.03 4
python dft_examples.py 0.01 5
python dft_examples.py 0.003 6
python pgd_examples.py co_occur 7
python pgd_examples.py dft 8
python pgd_examples.py direct 9
